[package]
edition = "2024"
name = "foreign_entity"
publish = false
version = "0.1.0"

[features]
default = ["outbound", "ports", "service"]
inbound = [
  "dep:axum",
  "dep:macro_authorization",
  "dep:model-error-response",
  "dep:utoipa",
  "entity_access/inbound",
  "ports",
  "service",
]
outbound = ["dep:filter_ast", "dep:sqlx", "ports"]
ports = ["dep:entity_access", "dep:item_filters", "dep:models_pagination", "dep:tokio"]
service = ["ports"]

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true, optional = true }
chrono = { workspace = true }
entity_access = { path = "../entity_access", optional = true, default-features = false, features = ["ports"] }
filter_ast = { path = "../filter_ast", optional = true }
item_filters = { path = "../item_filters", optional = true }
macro_authorization = { path = "../macro_authorization", optional = true, default-features = false, features = ["axum"] }
macro_user_id = { path = "../macro_user_id" }
macro_uuid = { path = "../macro_uuid" }
model-error-response = { path = "../model-error-response", optional = true }
models_pagination = { path = "../models_pagination", optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true, optional = true }
thiserror = { workspace = true }
tokio = { workspace = true, optional = true }
tracing = { workspace = true }
utoipa = { workspace = true, optional = true }
uuid = { workspace = true }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
http-body-util = { workspace = true }
macro_db_migrator = { path = "../macro_db_migrator" }
model_user = { path = "../model_user" }
rootcause = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tower = { workspace = true }
