[package]
default-run = "notification_service"
edition = "2024"
name = "notification_service"
publish = false
version = "0.1.0"

[[bin]]
name = "notification_service"
path = "src/main.rs"

[[bin]]
name = "notification_service_openapi"
path = "src/openapi.rs"

[[bin]]
name = "notification_service_doppler_config"
path = "src/doppler_config.rs"

[features]
default = ["push_notification_event_handler"]
local_queue = []
push_notification_event_handler = []

[dependencies]
anyhow = { workspace = true }
aws-sdk-secretsmanager = { workspace = true }
aws-sdk-sesv2 = { workspace = true }
aws-sdk-sns = { workspace = true }
aws-sdk-sqs = { workspace = true }
axum = { workspace = true }
chrono = { workspace = true }
database_env_vars = { path = "../../crates/database_env_vars" }
email_formatting = { path = "../../crates/email_formatting" }
hmac = { workspace = true }
http-body-util = { workspace = true }
itertools = { workspace = true }
last_online_tracker = { path = "../../crates/last_online_tracker" }
macro_auth = { path = "../../crates/macro_auth" }
macro_authorization = { path = "../../crates/macro_authorization", features = [
  "postgres",
] }
macro_aws_config = { path = "../../crates/macro_aws_config" }
macro_config = { path = "../../crates/macro_config" }
doppler-config = { workspace = true }
macro_cors = { path = "../../crates/macro_cors" }
macro_entrypoint = { path = "../../crates/macro_entrypoint" }
macro_env = { path = "../../crates/macro_env" }
macro_env_var = { path = "../../crates/macro_env_var" }
macro_event_broker = { path = "../../crates/macro_event_broker" }
agent_session_notifications = { path = "../../crates/agent_session_notifications" }
macro_middleware = { path = "../../crates/macro_middleware", default-features = false }
macro_queues = { path = "../../crates/macro_queues" }
macro_tower_layers = { path = "../../crates/macro_tower_layers" }
macro_user_id = { path = "../../crates/macro_user_id" }
macro_uuid = { path = "../../crates/macro_uuid" }
mention_utils = { path = "../../crates/mention_utils" }
model = { path = "../../crates/model" }
model-entity = { path = "../../crates/model-entity" }
model-error-response = { path = "../../crates/model-error-response" }
model_file_type = { path = "../../crates/model_file_type" }
model_notifications = { path = "../../crates/model_notifications" }
model_user = { path = "../../crates/model_user" }
models_pagination = { path = "../../crates/models_pagination", features = [
  "axum",
] }
notification = { path = "../../crates/notification", features = ["axum"] }
notification_db_client = { path = "../../crates/notification_db_client" }
paste = { workspace = true }
rate_limit = { path = "../../crates/rate_limit" }
redis = { workspace = true }
regex = { workspace = true }
secretsmanager_client = { path = "../../crates/secretsmanager_client" }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
sns_client = { path = "../../crates/sns_client" }
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true, features = ["compression-gzip"] }
tracing = { workspace = true }
url = { workspace = true }
utoipa = { workspace = true, features = ["chrono"] }
utoipa-swagger-ui = { workspace = true }
uuid = { workspace = true }

macro_service_urls = { path = "../../crates/macro_service_urls" }
workspace-hack = { version = "0.1", path = "../../crates/workspace-hack" }

[dev-dependencies]
macro_auth = { path = "../../crates/macro_auth", features = ["testing"] }
